# This is the default configuration file. Don't edit it directly, create a production.yaml or development.yaml file in
# the same directory to override the default values.
#
# All string values should be enclosed in quotes.

token: # Discord bot token - never share this with anyone!
applicationId: # Discord application ID

registerCommands: true # Whether to register commands with the Discord API on startup

database:
  filename: "methuselah.sqlite" # SQLite database file name
  logging: false # Enable database query logging
  synchronize: false # Whether to automatically synchronize the database schema on startup
  migrationsRun: true # Whether to run migrations on startup

log:
  type: "pretty" # Type of logging output (pretty, json, or hidden)
  minLevel: 3 # Minimum log level for the bot to output logs (1: trace, 2: debug, 3: info, 4: warn, 5: error, 6: fatal)