# This is the default configuration file. Don't edit it directly, create a production.yaml or development.yaml file in
# the same directory to override the default values.
#
# All string values should be enclosed in quotes.

token: # Discord bot token - never share this with anyone!
applicationId: # Discord application ID

log:
  type: "pretty" # Type of logging output (pretty, json, or hidden)
  minLevel: 3 # Minimum log level for the bot to output logs (1: trace, 2: debug, 3: info, 4: warn, 5: error, 6: fatal)