name: Deploy to production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=yes \
              -p "${{ secrets.SSH_PORT }}" \
              "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" << 'EOF'
            
            cd /home/discordbot/methuselah
            git pull origin production
            yarn install
            sudo systemctl restart methuselah
          EOF
        shell: bash
